### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by krooven**
updating urls for qgis integration.

### CODE REVIEW

**Comment by krooven** [comment]
Updated the english tiles. thanks for notify me for that.
The overlays are fine. they appear in the hebrew folder (works in qgis at least). mybe better to move them to separate folder, not very important to my opinion.

**Comment by zstadler** [comment]
I meant to say that the proper prefixes for the overlay URLs are https://israelhiking.osm.org.il/OverlayTiles/ and https://israelhiking.osm.org.il/OverlayMTB/

**Comment by mk4th** [comment]
Please update the (1) Israel Hiking Online.xml with the new address. (2) Add MTB map .xml file. (3) Refer users the MOBAC readme file for the creation of multi layer xml map source with the overlay tiles.  

It won't let me upload here the .xml files that I made.

**Comment by krooven** [comment]
Pls see following xml for ORUXMAPS. 
I dont see it in the repository.
The link menetion in readme.md https://israelhiking.osm.org.il/OruxMapsDownload.html is broken.

<?xml version="1.0" encoding="utf-8"?>
<onlinemapsources>

<onlinemapsource uid="972">
      <name>Israel Hiking Map (IL)</name>
      <url><![CDATA[https://israelhiking.osm.org.il/Hebrew/Tiles/{$z}/{$x}/{$y}.png]]></url>
      <website><![CDATA[<a href="http://IsraelHiking.osm.org.il">Israel Hiking Map</a>]]></website>
      <minzoom>7</minzoom>
      <maxzoom>16</maxzoom>
      <projection>MERCATORESFERICA</projection>
      <servers></servers>
      <httpparam name=""></httpparam>
      <cacheable>1</cacheable>
      <downloadable>1</downloadable>
      <xop></xop>
      <yop></yop>
      <zop></zop>
      <qop></qop>
    </onlinemapsource>
    <onlinemapsource uid="9722">
      <name>Israel MTB Map (IL)</name>
      <url><![CDATA[https://israelhiking.osm.org.il/Hebrew/mtbTiles/{$z}/{$x}/{$y}.png]]></url>
      <website><![CDATA[<a href="http://israelhiking.osm.org.il/IsraelMTBmap.html">Israel MTB Map</a>]]></website>
      <minzoom>7</minzoom>
      <maxzoom>16</maxzoom>
      <projection>MERCATORESFERICA</projection>
      <servers></servers>
      <httpparam name=""></httpparam>
      <cacheable>1</cacheable>
      <downloadable>1</downloadable>
      <xop></xop>
      <yop></yop>
      <zop></zop>
      <qop></qop>
    </onlinemapsource>
	<onlinemapsource uid="9723">
      <name>Israel Hiking Map - ENGLISH (IL)</name>
      <url><![CDATA[https://israelhiking.osm.org.il/English/Tiles/{$z}/{$x}/{$y}.png]]></url>
      <website><![CDATA[<a href="http://IsraelHiking.osm.org.il">Israel Hiking Map</a>]]></website>
      <minzoom>7</minzoom>
      <maxzoom>16</maxzoom>
      <projection>MERCATORESFERICA</projection>
      <servers></servers>
      <httpparam name=""></httpparam>
      <cacheable>1</cacheable>
      <downloadable>1</downloadable>
      <xop></xop>
      <yop></yop>
      <zop></zop>
      <qop></qop>
    </onlinemapsource>
	<onlinemapsource uid="9724">
      <name>Israel MTB Map - ENGLISH (IL)</name>
      <url><![CDATA[https://israelhiking.osm.org.il/English/mtbTiles/{$z}/{$x}/{$y}.png]]></url>
      <website><![CDATA[<a href="http://IsraelHiking.osm.org.il">Israel MTB Map</a>]]></website>
      <minzoom>7</minzoom>
      <maxzoom>16</maxzoom>
      <projection>MERCATORESFERICA</projection>
      <servers></servers>
      <httpparam name=""></httpparam>
      <cacheable>1</cacheable>
      <downloadable>1</downloadable>
      <xop></xop>
      <yop></yop>
      <zop></zop>
      <qop></qop>
    </onlinemapsource>
</onlinemapsources>

**Comment by HarelM** [comment]
You are right.
The instructions and ability to download are now at: https://israelhiking.osm.org.il/#!/?download
The entire section is probably not needed any more...

**Comment by krooven** [comment]
Maybe I misunderstood but the links lead to the OFFLINE download.
I think the xml is still useful, as it gives the users access to the online maps, without the need to download them.

**Comment by krooven** [comment]
OK I got it
The xml I post here is for ORUXMAPS user, not for MOBAC.
I believe it need to be a separate resource.

**Comment by HarelM** [comment]
There are oruxmaps xml files in the following folder:
https://github.com/IsraelHikingMap/Map/tree/master/Mobile%20Atlas%20Creator/mapsources
The original link `OruxMapsDownload.html` was pointing to a download page which I replaced with the dialog in the site.

**Comment by HarelM** [comment]
I have updated the readme with the relevant instructions and links.
If you find any other issues please let us know.

**Pull request merged**
